package tachiyomi.tts.tiktok

import java.util.Locale

data class TikTokVoice(
    val id: String,
    val name: String,
    val languageTag: String,
)

fun TikTokVoice.displayName(locale: Locale = Locale.getDefault()): String =
    "$name (${Locale.forLanguageTag(languageTag).getDisplayLanguage(locale)})"

object TikTokVoiceCatalog {
    val voices = listOf(
        TikTokVoice("BV074_streaming", "Cô gái hoạt ngôn", "vi"),
        TikTokVoice("BV421_vivn_streaming", "Cô gái ngọt ngào", "vi"),
        TikTokVoice("BV075_streaming", "Thanh niên tự tin", "vi"),
        TikTokVoice("vi_female_huong", "Giọng nữ phổ thông", "vi"),
        TikTokVoice("en_us_002", "Jessie", "en"),
        TikTokVoice("en_male_jomboy", "Game On", "en"),
        TikTokVoice("en_male_funny", "Wacky", "en"),
        TikTokVoice("en_us_ghostface", "Scream", "en"),
        TikTokVoice("en_female_samc", "Empathetic", "en"),
        TikTokVoice("en_male_cody", "Serious", "en"),
        TikTokVoice("en_female_makeup", "Beauty Guru", "en"),
        TikTokVoice("en_female_richgirl", "Bestie", "en"),
        TikTokVoice("en_male_grinch", "Trickster", "en"),
        TikTokVoice("en_us_006", "Joey", "en"),
        TikTokVoice("en_male_narration", "Story Teller", "en"),
        TikTokVoice("en_male_deadpool", "Mr. GoodGuy", "en"),
        TikTokVoice("en_uk_001", "Narrator", "en"),
        TikTokVoice("en_uk_003", "Male English UK", "en"),
        TikTokVoice("en_au_001", "Metro", "en"),
        TikTokVoice("en_male_jarvis", "Alfred", "en"),
        TikTokVoice("en_male_ashmagic", "ashmagic", "en"),
        TikTokVoice("en_male_olantekkers", "olantekkers", "en"),
        TikTokVoice("en_male_ukneighbor", "Lord Cringe", "en"),
        TikTokVoice("en_male_ukbutler", "Mr. Meticulous", "en"),
        TikTokVoice("en_female_shenna", "Debutante", "en"),
        TikTokVoice("en_female_pansino", "Varsity", "en"),
        TikTokVoice("en_male_trevor", "Marty", "en"),
        TikTokVoice("en_female_f08_twinkle", "Pop Lullaby", "en"),
        TikTokVoice("en_male_m03_classical", "Classic Electric", "en"),
        TikTokVoice("en_female_betty", "Bae", "en"),
        TikTokVoice("en_male_cupid", "Cupid", "en"),
        TikTokVoice("en_female_grandma", "Granny", "en"),
        TikTokVoice("en_male_m2_xhxs_m03_christmas", "Cozy", "en"),
        TikTokVoice("en_male_santa_narration", "Author", "en"),
        TikTokVoice("en_male_sing_deep_jingle", "Caroler", "en"),
        TikTokVoice("en_male_santa_effect", "Santa", "en"),
        TikTokVoice("en_female_ht_f08_newyear", "NYE 2023", "en"),
        TikTokVoice("en_male_wizard", "Magician", "en"),
        TikTokVoice("en_female_ht_f08_halloween", "Opera", "en"),
        TikTokVoice("en_female_ht_f08_glorious", "Euphoric", "en"),
        TikTokVoice("en_male_sing_funny_it_goes_up", "Hypetrain", "en"),
        TikTokVoice("en_female_ht_f08_wonderful_world", "Melodrama", "en"),
        TikTokVoice("en_male_m2_xhxs_m03_silly", "Quirky Time", "en"),
        TikTokVoice("en_female_emotional", "Peaceful", "en"),
        TikTokVoice("en_male_m03_sunshine_soon", "Toon Beat", "en"),
        TikTokVoice("en_female_f08_warmy_breeze", "Open Mic", "en"),
        TikTokVoice("en_male_m03_lobby", "Jingle", "en"),
        TikTokVoice("en_male_sing_funny_thanksgiving", "Thanksgiving", "en"),
        TikTokVoice("en_female_f08_salut_damour", "Cottagecore", "en"),
        TikTokVoice("en_us_007", "Professor", "en"),
        TikTokVoice("en_us_009", "Scientist", "en"),
        TikTokVoice("en_us_010", "Confidence", "en"),
        TikTokVoice("en_au_002", "Smooth", "en"),
        TikTokVoice("en_us_chewbacca", "Chewbacca", "en"),
        TikTokVoice("en_us_c3po", "C3PO", "en"),
        TikTokVoice("en_us_stitch", "Stitch", "en"),
        TikTokVoice("en_us_stormtrooper", "Stormtrooper", "en"),
        TikTokVoice("en_us_rocket", "Rocket", "en"),
        TikTokVoice("en_female_madam_leota", "Madame Leota", "en"),
        TikTokVoice("en_male_ghosthost", "Ghost Host", "en"),
        TikTokVoice("en_male_pirate", "Pirate", "en"),
        TikTokVoice("fr_001", "French - Male 1", "fr"),
        TikTokVoice("fr_002", "French - Male 2", "fr"),
        TikTokVoice("es_002", "Spanish (Spain) - Male", "es"),
        TikTokVoice("es_mx_002", "Spanish MX - Male", "es"),
        TikTokVoice("br_001", "Portuguese BR - Female 1", "pt"),
        TikTokVoice("br_003", "Portuguese BR - Female 2", "pt"),
        TikTokVoice("br_004", "Portuguese BR - Female 3", "pt"),
        TikTokVoice("br_005", "Portuguese BR - Male", "pt"),
        TikTokVoice("bp_female_ivete", "Ivete Sangalo", "pt"),
        TikTokVoice("bp_female_ludmilla", "Ludmilla", "pt"),
        TikTokVoice("pt_female_lhays", "Lhays Macedo", "pt"),
        TikTokVoice("pt_female_laizza", "Laizza", "pt"),
        TikTokVoice("pt_male_bueno", "Galvão Bueno", "pt"),
        TikTokVoice("de_001", "German - Female", "de"),
        TikTokVoice("de_002", "German - Male", "de"),
        TikTokVoice("id_001", "Indonesian - Female", "id"),
        TikTokVoice("jp_001", "Japanese - Female 1", "ja"),
        TikTokVoice("jp_003", "Japanese - Female 2", "ja"),
        TikTokVoice("jp_005", "Japanese - Female 3", "ja"),
        TikTokVoice("jp_006", "Japanese - Male", "ja"),
        TikTokVoice("jp_female_fujicochan", "りーさ", "ja"),
        TikTokVoice("jp_female_hasegawariona", "世羅鈴", "ja"),
        TikTokVoice("jp_male_keiichinakano", "Morio’s Kitchen", "ja"),
        TikTokVoice("jp_female_oomaeaika", "夏絵ココ", "ja"),
        TikTokVoice("jp_male_yujinchigusa", "低音ボイス", "ja"),
        TikTokVoice("jp_female_shirou", "四郎", "ja"),
        TikTokVoice("jp_male_tamawakazuki", "玉川寿紀", "ja"),
        TikTokVoice("jp_female_kaorishoji", "庄司果織", "ja"),
        TikTokVoice("jp_female_yagishaki", "八木沙季", "ja"),
        TikTokVoice("jp_male_hikakin", "ヒカキン", "ja"),
        TikTokVoice("jp_female_rei", "丸山礼", "ja"),
        TikTokVoice("jp_male_shuichiro", "修一朗", "ja"),
        TikTokVoice("jp_male_matsudake", "マツダ家の日常", "ja"),
        TikTokVoice("jp_female_machikoriiita", "まちこりーた", "ja"),
        TikTokVoice("jp_male_matsuo", "モジャオ", "ja"),
        TikTokVoice("jp_male_osada", "モリスケ", "ja"),
        TikTokVoice("kr_002", "Korean - Male 1", "ko"),
        TikTokVoice("kr_003", "Korean - Female", "ko"),
        TikTokVoice("kr_004", "Korean - Male 2", "ko"),
    )

    fun find(id: String?): TikTokVoice? = voices.find { it.id == id }

    fun defaultFor(locale: Locale): TikTokVoice =
        voices.firstOrNull { it.languageTag == locale.language } ?: voices.first()
}
