blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://nekori.yuneko.dev/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🖥️ Nekori website
    url: https://nekori.yuneko.dev/
    about: Guides, troubleshooting, and answers to common questions
