package eu.kanade.tachiyomi.jsruntime

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import eu.kanade.tachiyomi.jsruntime.spec.NativeHostApiSpec

/**
 * The TurboModule. Its base class is generated by React Native codegen from
 * `js-runtime/specs/NativeHostApi.ts`, so neither side of the contract can drift silently.
 *
 * All logic lives in [JsCallDispatcher]; this class only bridges. React Native owns the instance
 * lifecycle, so the dispatcher is told when one appears and when one goes away.
 */
internal class NativeHostApiModule(
    reactContext: ReactApplicationContext,
) : NativeHostApiSpec(reactContext) {

    init {
        JsCallDispatcher.attach(this)
    }

    /** `emitOnCommand` is `protected` on the generated spec; the dispatcher needs it. */
    fun emitCommand(command: ReadableMap) {
        emitOnCommand(command)
    }

    override fun ready() {
        JsCallDispatcher.onJsReady()
    }

    override fun resolve(id: String, json: String) {
        JsCallDispatcher.resolve(id, json)
    }

    override fun reject(id: String, message: String) {
        JsCallDispatcher.reject(id, message)
    }

    override fun invalidate() {
        JsCallDispatcher.detach(this)
        super.invalidate()
    }
}
